### PR TITLE
Test coverage!

### PR DESCRIPTION
**Pull request by eytanbiala**
We've added some tests as part of the [CocoaPods Test Jam](http://cocoapods.org/testjam)!

### CODE REVIEW

**Comment by spacedrabbit** [comment]
Thanks for making an awesome pod, @kevin-hirsch. I'm glad myself and @eytanbiala could contribute back to this project for Test Jam. It was great working with you as well, @eytanbiala

**Comment by kevin-hirsch** [comment]
Thank you very much! You did great work @eytanbiala and @spacedrabbit :)
I will merge your pull request!

**Comment by eytanbiala** [comment]
Happy to contribute! You may want to setup Travis and Coveralls for your repo and update the badges in the readme, since they currently point to the fork.

**Comment by kevin-hirsch** [comment]
Yes, I saw this. I will change it later ;)
Again, thanks a lot ! :+1:

**Comment by eytanbiala** [comment]
Cool, thanks!

**Pull request merged**
