### PR TITLE
added tap block to HUD

### PR DESCRIPTION
**Pull request by sdgandhi**
Added a tap block parameter that can be set to perform the block when the HUD is tapped.

### CODE REVIEW

**Comment by kevin-hirsch** [comment]
Hello @sdgandhi, can you precise what you did?

**Comment by sdgandhi** [comment]
@kevin-hirsch, updated the description

**Comment by kevin-hirsch** [comment]
Is it really needed to propose the user to provide a block when view is tapped. Could it be different than dismissing the HUD on tap?
And if we change the block property on tap for an automatic dismissing action, would it be great to add a small text in light gray underneath the status that tells something like: "Tap to dismiss"
Something that will love like this:

**Comment by sdgandhi** [comment]
Yeah, I added the block because we needed a "tap to cancel" action for a long running operation. I agree a detail label would be better. I will try to add that but am pretty busy at the moment.

**Comment by kevin-hirsch** [comment]
No problem, I am kind of busy too but when I have time I will merge your modifications and add a detail label ;)

**Comment by KiranPanesar** [comment]
I was planning on implementing this to do a "tap to retry HTTP request" HUD.

**Comment by kevin-hirsch** [comment]
It is indeed different. So if your request is too long, the user could tap on the hud to re-call the request?

**Comment by KiranPanesar** [comment]
I was planning on showing an ```errorWithStatus:``` HUD saying "tap to retry".

We're only using this functionality in one small place in our app, so I've 'hacked' around it for now, by showing the error HUD and then adding a tap gesture recogniser to it.

**Comment by kevin-hirsch** [comment]
Ok, I see. A callback could be great to start with. I'll merge your code today ;)

**Comment by sdgandhi** [comment]
@KiranPanesar I'm pretty sure you could use the tapblock in this PR from the "show with error" version of kvn progress.

**Comment by KiranPanesar** [comment]
@sdgandhi Yeah, I'll switch to that when it gets merged. I just don't want to move our codebase off of the main cocoapod to your fork. We don't know how long it'll take for this to get merged, and I don't want to miss out on any other fixes done on master/cocoapod.

**Comment by kevin-hirsch** [comment]
Hello @sdgandhi & @KiranPanesar, 

A lot of things and structure has changed so I decided to take part of this pull request code to include it myself in the latest version of this project. It would have been longer to handle the merge conflicts ;)
So it is now done and available in this commit: 07a107b14d8cf5570bdec376703c0ac4b05c2fc8
And it is part of the version 1.2.7 in Cocoapods ;)

**Pull request closed without merging**
