### PR TITLE
Added stop button

### PR DESCRIPTION
**Pull request by kronik**
Hey! Found your progress dialog the best. But it's missing one important thing others (MRProgress and etc) have - stop indicator / button. So I've added one. Please check my changes and consider them for integration. Thanks!

### CODE REVIEW

**Comment by kevin-hirsch** [comment]
Hello @kronik, it is a very good idea! :)
I will integrate/merge your changes tomorrow (GMT+1)
:+1:

**Comment by kronik** [comment]
Any updates?

**Comment by kevin-hirsch** [comment]
I merged your changes. I did add some customization for the stop button in an extra commit (c744240d6bdfd7933b8fbe32cbd9be41655eb000):

```objc
/**
 * Tells wether the stop squared button will be shown in the middle of a progress circle or not.
 * @remark If no <code>tapBlock</code> is configured, <code>showStop</code> will have no effect.
 * <code>tapBlock</code> is executed when the stop button is pressed.
 * @see <code>tapBlock</code>
 */
@property (nonatomic, getter = doesShowStop) BOOL showStop;

/** Relative height of the stop squared button. Between 0 and 1. For example: 0.3 will display a square that has 30% de size of the circle. */
@property (nonatomic) CGFloat stopRelativeHeight;
```

Thanks to you!

**Comment by kronik** [comment]
Cool! Cheers 👍🏼

**Pull request merged**
